mozilla/crlite

create_filter_cascade/read_keys.py
This was useful while diagnosing #72.
=> Add a query mechanism to read_keys.py

moz_kinto_publisher/main.py
Basically the line at 747 `for record in ro_client.get_records` was getting incoherent data since it was reading from the read-only URL, while the read-write URL had a staged update, causing the exceptions (and diagnostic breakpoint) here to trigger:
https://github.com/mozilla/crlite/blob/3a6e2c0bc8f1e5d844adb50eed0c7b38688add3d/moz_kinto_publisher/main.py#L829-L832
=> Publisher ro/rw cleanup

.circleci/config.yml, containers/README.md, containers/build-local.sh, containers/cloudbuild.yaml, containers/crlite-config.properties.example, containers/crlite-publish-config.properties.example, containers/crlite-publish/pod.yaml, containers/crlite-signoff-config.properties.example, containers/crlite-signoff/Dockerfile, containers/crlite-signoff/crlite-signoff-tool.py, containers/crlite-signoff/crlite-signoff.sh, containers/crlite-signoff/pod.yaml, moz_kinto_publisher/main.py
=> Fix #58 - Add a pod to automatically sign-off on Kinto changes if valid

containers/Dockerfile
=> Use Debian Buster and Python 3.8

.circleci/config.yml
=> Rename staging to dev

containers/crlite-generate/crlite-generate.sh, go/cmd/aggregate-crls/aggregate-crls.go, go/cmd/aggregate-crls/aggregate-crls_test.go, go/cmd/aggregate-crls/crl-auditor.go, go/cmd/aggregate-crls/crl-auditor_test.go, go/cmd/aggregate-crls/download-auditor.go, go/cmd/aggregate-crls/download-auditor_test.go, go/rootprogram/issuers.go, go/rootprogram/issuers_test.go, workflow/0-allocate_identifier
This PR enables `aggregate-crls` to produce a `crl-audit.json` file on each run which contains a succinct form of all the CRL errors encountered while attempting to update revocations. As an example:
```json
{
"Entries": [
{
"Timestamp": "2020-07-10T04:42:55.139524Z",
"Url": "http://crl.godaddy.com/gdig2s1-629.crl",
"Issuer": "8Rw90Ej3Ttt8RRkrg-WYDS9n7IS03bk5bjP_UXPtaY8=",
"IssuerSubject": "CN=Go Daddy Secure Certificate Authority - G2,OU=http://certs.godaddy.com/repository/,O=GoDaddy.com\\, Inc.,L=Scottsdale,ST=Arizona,C=US",
"Kind": "Failed Verify",
"Error": "[/tmp/crlite/persistent/crls/8Rw90Ej3Ttt8RRkrg-WYDS9n7IS03bk5bjP_UXPtaY8=/crl.godaddy.com-gdig2s1-629-bbade061306daa08.crl.tmp] CRL is older than the previous CRL (previous=2020-07-09 18:38:45 +0000 UTC, this=2020-07-08 18:37:15 …
```
=> Produce a CRL audit report

moz_kinto_publisher/main.py
=> Catch exceptions that might be thrown by `is_expired`

go/cmd/aggregate-crls/aggregate-crls.go, go/go.mod, go/rootprogram/issuers.go, go/rootprogram/issuers_test.go
=>  Emit a gauge for "age of CCADB data" from aggregate-crls

.circleci/config.yml, .pre-commit-config.yaml, containers/scripts/crlite-signoff-tool.py, moz_kinto_publisher/main.py, moz_kinto_publisher/test_publisher.py, workflow/__init__.py
Also, let's pin to that version for now, because changing is annoying!
=> Move to Black 20.8b1

containers/scripts/crlite-signoff-tool.py
This fixes #130 by using a new `--check-freshness X` flag for `moz_crlite_query` added in https://github.com/mozilla/moz_crlite_query/pulls, v0.3.6.
This also adds an environment variable `CRLITE_FRESHNESS_HOURS` which defaults to `2`, which seems like a reasonable maximum age if the task is running every hour. We could set that to `6` and just be sure we are never signing previous runs' changes, I suppose, but we wanted to be conservative, so I set the default conservatively.
This also depends on the `--structured` PR, just so that it can rebase cleanly, since I expect that to land first.
=> Have Signoff Tool obtain the filters from the Kinto Staging to-be-signed collection

moz_kinto_publisher/main.py
Work in progress
Resolves #153
Resolves #172
=> Issue #172: Improvements to moz_kinto_publisher

.gitignore, go/cmd/aggregate-crls/aggregate-crls.go, go/cmd/aggregate-crls/aggregate-crls_test.go, go/cmd/aggregate-known/aggregate-known.go, go/cmd/ct-fetch/ct-fetch.go, go/engine/engine.go, go/go.mod, go/storage/certdatabase.go, go/storage/certdatabase_test.go, go/storage/filesystemdatabase.go, go/storage/filesystemdatabase_test.go, go/storage/issuermetadata.go, go/storage/issuermetadata_test.go, go/storage/storagebackend_tests.go, go/storage/types.go
Dana, the first three commits here were on the dev branch when I started working. I've reviewed them and everything looks good except for one [dropped call](https://github.com/mozilla/crlite/commit/2b08211f078cf7ebfb4a9271a7e8e66e53bfcc2d#diff-460fe8ae10fb702dc5989fca37f03c2388180b7c5f77939344d239dc9a0dbe19L185) to IssuerMetadata.Accumulate.
Requesting your review just for the last commit in this sequence, which adds that call back in. The last commit also cleans up some unnecessarily complex (and unsafe) lock manipulations in the Accumulate method. I can break the cleanup into a separate PR if you'd like.
This code has been tested on dev.
=> Land dev branch backlog

moz_crlite_lib/moz_crlite_lib/__init__.py, moz_crlite_lib/moz_crlite_lib/crlite_lib_test.py
This has been tested on dev.
Resolves #152
=> Fix Issue #152: make it clear that expectRead needs buffered io

containers/scripts/crlite-signoff-tool.py, create_filter_cascade/certs_to_crlite.py, create_filter_cascade/read_keys.py, moz_crlite_lib/moz_crlite_lib/__init__.py, workflow/1-generate_mlbf, workflow/2-upload_artifacts_to_storage, workflow/__init__.py
=> Use python-glog for all logging

moz_kinto_publisher/main.py
=> moz_kinto_publisher: remove ro_client

containers/scripts/crlite-signoff-tool.py, create_filter_cascade/certs_to_crlite.py, create_filter_cascade/read_keys.py, moz_crlite_lib/moz_crlite_lib/__init__.py, moz_kinto_publisher/main.py, workflow/1-generate_mlbf, workflow/2-upload_artifacts_to_storage, workflow/__init__.py
All of these PRs have been reviewed and merged onto the landing branch. This PR is to move them to main.
* #186 
* #183
=> Land changes from #183 and #186

moz_kinto_publisher/main.py, moz_kinto_publisher/test_publisher.py
=> moz_kinto_publisher: Publish filter coverage

containers/scripts/crlite-signoff-tool.py, containers/scripts/crlite-signoff.sh, moz_kinto_publisher/main.py, moz_kinto_publisher/settings.py
Whoops, this didn't actually make it last time.
* #199
=> Land changes from #199

moz_kinto_publisher/main.py
=> moz_kinto_publisher: Fix Issue #203

moz_kinto_publisher/main.py, moz_kinto_publisher/test_publisher.py
=> Use remote settings records for filter age test

moz_kinto_publisher/main.py
=> moz_kinto_publisher: skip ctlog data with empty LogID

containers/scripts/crlite-signoff-tool.py, moz_kinto_publisher/main.py, moz_kinto_publisher/test_publisher.py
* #208
* #210
* #211
* #212
resolves #205, #206, #209
=> Land changes from #208, #210, #211, #212

moz_kinto_publisher/main.py
=> moz_kinto_publisher: adjust coverage by MMD

go/cmd/ct-fetch/ct-fetch.go, go/storage/certdatabase.go, go/storage/mockcache.go, go/storage/rediscache.go, go/storage/types.go, setup.py
Commit ad65b2a resolves #218. The three commits that follow are minor changes. Commit a2c5f29 resolves #220. Commit 7432053 resolves #222.
=> Final changes for v1.0.6

go/cmd/aggregate-crls/aggregate-crls.go
=> aggregate-crls: enroll issuers with accessible but empty CRLs

moz_kinto_publisher/main.py
=> moz_kinto_publisher: Update enrollment only when a full filter is published 

Pipfile, moz_kinto_publisher/main.py, moz_kinto_publisher/test_publisher.py, setup.py
=> Clean up after kinto-http upgrade

moz_kinto_publisher/main.py
Resolves #236 
Note: `remote_expired` constructed on line 555 is a subset of `remote_only`. So there's no need to delete expired certs in a separate loop.
=> Delete remote intermediates not on local list

containers/scripts/crlite-signoff-tool.py
=> signoff-tool: fix parsing of aggregator records

moz_kinto_publisher/main.py
Resolves #246 
**note:** Wait until schema changes have been approved before merging.
=> moz_kinto_publisher: publish policy fields for ct-logs

containers/scripts/crlite-signoff-tool.py, containers/scripts/crlite-signoff.sh
This reverts commits eed4a1bf9c3d160b10c83b977919a80d5e41d516, 181cccaa4aaec286ce048e42de37ffc2b1346f74, and a3f271cec752ab2156e3c51cecc8ac4894a4930a.
Resolves #248
=> signoff-tool: Remove enrollment tests

containers/scripts/crlite-generate.sh, go/storage/localdiskbackend.go, workflow/2-upload_artifacts_to_storage
A few small changes that save ~20 minutes on the generate task. Both have been tested on the dev environment.
=> Performance improvements for the generate task

containers/Dockerfile, workflow/1-generate_mlbf
=> Enable sha256 filters

rust-query-crlite/src/main.rs
Some hosts in our `verification-domains.txt` file consistently reset the first TLS connection that we make. This seems to be some kind of DDoS countermeasure (it happens w/ other tools like openssl s_client). So let's try connections twice.
=> rust-query-crlite: retry tls connections on first failure

rust-query-crlite/src/main.rs
I overlooked the `raw_serial()` method on `x509_parser::TbsCertificate`. Under the hood it calls `der_parser::parse_ber_integer` https://docs.rs/der-parser/latest/src/der_parser/ber/parser.rs.html#280-295, which is exactly what we want.
=> rust-query-crlite: handle negative serial numbers

go/cmd/ct-fetch/ct-fetch.go
=> ct-fetch: include CA certs

go/cmd/aggregate-crls/aggregate-crls.go, go/cmd/aggregate-crls/aggregate-crls_test.go, go/rootprogram/issuers.go, go/rootprogram/issuers_test.go
Resolves #270 
Note that this does not yet include a countermeasure against the attack [described recently on dev-security-policy](https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/qhrGxLvyreU). We can revisit this if/when the policy is updated with a countermeasure.
=> aggregate-crls: Use CRLs from CCADB

go/cmd/ct-fetch/ct-fetch.go
=> ct-fetch: retry downloads for some network errors

go/cmd/ct-fetch/ct-fetch.go
=> ct-fetch: fix firstIndex for init job on CT log with few entries

go/cmd/aggregate-known/aggregate-known.go
Resolves #280 
I tested this on dev. Here's the memory usage before (< 1pm) and after (> 1pm):
In the before graph, the drop around 12:30 is the end of aggregate-known, and the final spike before that is loading serials from Let's Encrypt. We have enough certs from LE now that we were getting consistent OOM failures there. 
In the after graph, the initial bump at 1:05 is in aggregate-crls. It has the same issue as aggregate-known, but the number of serials is much less. I'm going to avoid tinkering with it for now. The main point is that the memory usage in aggregate-known is negligible.
The memory usage in the last half hour of both images is when we're actually generating the filter. We haven't seen OOM issues there, but I'm running a heap profiler on a local instance to see if I can …
=> aggregate-known: avoid keeping an issuer's full serial list in memory

rust-query-crlite/Cargo.toml
Update a couple of dependencies to pick up new signature algorithm support, etc.
=> Update rust-query-crlite dependencies

containers/scripts/crlite-generate.sh, moz_kinto_publisher/main.py, moz_kinto_publisher/test_publisher.py
Start publishing clubcard-based delta updates on a new `experimental+deltas` channel. Also stop publishing the `specified` and `priority` channels.
=> Add a new "experimental+deltas" filter channel

go/storage/certdatabase.go, go/storage/certdatabase_test.go
It turns out that one issuer in our database has certificates with ~17000 distinct expiry-hour values (about 2 years worth if they're sequential). We hit a `runtime: program exceeds 10000-thread limit` error while processing that issuer. It's not clear to me why the go scheduler doesn't handle this for us..
This PR makes it so we process no more than 1000 expiry-hour bins at a time.
=> storage: limit number of goroutines used in moveCachedSerialsToStorage

moz_kinto_publisher/main.py, moz_kinto_publisher/test_publisher.py
Splitting this out of #359 so that we can do some manual testing with remote settings before pushing the other changes from #359 to the staging environment.
=> moz_kinto_publisher: add tiled logs to remote settings ct-logs collection

setup/list_all_active_ct_logs
=> remove setup/list_all_active_ct_logs
